default:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: blair
      password: "{{ env_var('PGPASSWORD') }}"
      port: 5432
      dbname: analytics
      schema: silver
      threads: 1
  target: dev

