bronze_to_silver:
  outputs:
    dev:
      dbname: grafana
      host: localhost
      keepalives_idle: 0
      password: grafana
      port: 5432
      schema: bronze
      sslmode: disable
      threads: 2
      type: postgres
      user: grafana
  target: dev
metadb:
  outputs:
    dev:
      dbname: grafana
      host: localhost
      pass: grafana
      port: 5432
      schema: bronze
      threads: 1
      type: postgres
      user: grafana
  target: dev
