# ✅ Filename: dbt_project.yml
# 📦 Purpose: Aligns with the 'metadb' profile in ~/.dbt/profiles.yml

name: bronze_dbt
version: "1.0"
profile: metadb  # 🔧 fixed from 'default' to 'metadb'

model-paths: ["models"]  # 🔧 renamed from deprecated 'source-paths'

models:
  bronze_dbt:
    +schema: public_bronze

