site_name: Open Source Analytics Platform
use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.top
    - search.highlight

nav:
  - Home: index.md
  - Key Concepts:
      - Performance Terminology: PerformanceTerms.md
      - Agile Kanban: Kanban.md
      - Objectives and Key Results: OKRs.md
      - Design Thinking: DesignThinking.md
      - Analytics Architectures: Architectures.md
      - Governance Frameworks: GovernanceFrameworks.md
      - Markdown Guide: MarkdownGuide.md
      - Mermaid Diagrams: MermaidDiagrams.md
      
  - Stack:
      - Raspberry Pi: RPi5.md
      - Comparisons: StackComparisons.md
      - DE Skills: SkillLevels.md
      - Analytics Deck: https://docs.google.com/presentation/d/1ACAE7UquavbQ15peb3CnmLqfQYJWLGAMXQ0OkgR-TMc/edit?usp=sharing
      - Apps:
          - Metabase: https://metabase.hoveto.ca
          - Grafana: https://grafana.hoveto.ca
          - dbt Docs: https://dbt.hoveto.ca
          - Dagster: https://dagster.hoveto.ca
          - Prometheus: https://prometheus.hoveto.ca
  - DMBOK:
      - Data Governance: 01_governance/index.md
      - Data Architecture: 02_architecture/index.md
      - Data Modeling and Design: 03_modeling/index.md
      - Data Storage and Operations: 04_storage/index.md
      - Data Security: 05_security/index.md
      - Data Integration and Interoperability: 06_integration/index.md
      - Document and Content Management: 07_content/index.md
      - Reference and Master Data: 08_masterdata/index.md
      - Data Warehousing and Business Intelligence: 09_warehousing/index.md
      - Metadata Management: 10_metadata/index.md
      - Data Quality: 11_quality/index.md
      - DMBOK Glossary: glossary.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
      fallback_to_build_date: true

extra:
  include_last_updated: true
  footer:
    <small>
      <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
        <img src="https://licensebuttons.net/l/by/4.0/88x31.png" alt="CC BY 4.0" style="height:20px; vertical-align:middle;" />
        Content licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)
      </a>
    </small>

markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - extra.js

extra_css:
  - stylesheets/mermaid.css
