site_name: Open Source Analytics Platform
use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.top
    - search.highlight

nav:
  - Home: index.md
  - Concepts:
      - GM Top 10: concepts/GMTop10.md
      - AI in Water: concepts/AiInWater.md
      - Insights as a Service: concepts/InsightsAsAService.md
      - Data Seven V's: concepts/SevenVs.md
      - Cognitive Biases: concepts/CognitiveBiases.md
      - Utility Theory: concepts/UtilityTheory.md
      - CMMi: concepts/CMMi.md
      - OKR: concepts/OKROverview.md
      - Value/Effort: concepts/ValueEffort.md
      - Design Thinking: concepts/DesignThinking.md
      - Kanban: concepts/Kanban.md
      - Agile@Scale: concepts/AgileAtScale.md
      - WIMS: concepts/Wims.md

  - Data Warehouse:
      - Governance: warehouse/Governance.md
      - Architectures: warehouse/Architectures.md
      - Tiered Analytics: warehouse/TieredAnalytics.md
      - Harmonization: warehouse/Harmonization.md
      - Terminology: warehouse/Terminology.md

  - Cyber:
      - NIST CSF: cyber/NISTCSF.md
      - NIST RMF: cyber/NISTRMF.md
      - NIST Risk Assessment: cyber/NISTGuide.md
      - Purdue Model: cyber/PurdueModel.md 
      
  - Stack:
      - Raspberry Pi: stack/RPi5.md
      - Comparisons: stack/StackComparisons.md
      - DE Skills: stack/SkillLevels.md
      - Analytics Deck: https://docs.google.com/presentation/d/1ACAE7UquavbQ15peb3CnmLqfQYJWLGAMXQ0OkgR-TMc/edit?usp=sharing
      - Apps:
          - Metabase: https://metabase.hoveto.ca
          - Grafana: https://grafana.hoveto.ca
          - dbt Docs: https://dbt.hoveto.ca
          - Dagster: https://dagster.hoveto.ca
          - Prometheus: https://prometheus.hoveto.ca
          - MkDocs (this!): https://mkdocs.hoveto.ca

  - DMBOK:
      - Data Governance: dmbok/01_governance/index.md
      - Data Architecture: dmbok/02_architecture/index.md
      - Data Modeling and Design: dmbok/03_modeling/index.md
      - Data Storage and Operations: dmbok/04_storage/index.md
      - Data Security: dmbok/05_security/index.md
      - Data Integration and Interoperability: dmbok/06_integration/index.md
      - Document and Content Management: dmbok/07_content/index.md
      - Reference and Master Data: dmbok/08_masterdata/index.md
      - Data Warehousing and Business Intelligence: dmbok/09_warehousing/index.md
      - Metadata Management: dmbok/10_metadata/index.md
      - Data Quality: dmbok/11_quality/index.md
      - DMBOK Glossary: dmbok/glossary.md

  - Markdown:
      - Markdown Guide: guide/MarkdownGuide.md
      - Mermaid Diagrams: guide/MermaidDiagrams.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
      fallback_to_build_date: true

extra:
  include_last_updated: true
  footer:
    <small>
      <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
        <img src="https://licensebuttons.net/l/by/4.0/88x31.png" alt="CC BY 4.0" style="height:20px; vertical-align:middle;" />
        Content licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)
      </a>
    </small>

markdown_extensions:
  - attr_list
  - pymdownx.extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.tasklist
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - extra.js

extra_css:
  - stylesheets/mermaid.css
