site_name: RPi5 Open Source Analytics Platform
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.top
    - search.highlight

nav:
  - Home: index.md
  - DMBOK:
      - Data Governance: 01_governance/index.md
      - Data Architecture: 02_architecture/index.md
      - Data Modeling and Design: 03_modeling/index.md
      - Data Storage and Operations: 04_storage/index.md
      - Data Security: 05_security/index.md
      - Data Integration and Interoperability: 06_integration/index.md
      - Document and Content Management: 07_content/index.md
      - Reference and Master Data: 08_masterdata/index.md
      - Data Warehousing and Business Intelligence: 09_warehousing/index.md
      - Metadata Management: 10_metadata/index.md
      - Data Quality: 11_quality/index.md
      - DMBOK Glossary: DmbokGlossary.md

  - Key Concepts:
    - Performance Terminology: PerformanceTerms.md
    - Agile Kanban: Kanban.md
    - Objectives and Key Results: OKRs.md
    - Design Thinking: DesignThinking.md
    - Analytics Architectures: Architectures.md
    - Governance Frameworks: GovernanceFrameworks.md
    - Mermaid Diagrams: MermaidDiagrams.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
      fallback_to_build_date: true

extra:
  include_last_updated: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.4.0/dist/mermaid.min.js
  - extra.js

extra_css:
  - stylesheets/mermaid.css